site_name: callmeryan.top
site_url: https://callmeryan.top

theme: 
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - search.suggest
  custom_dir: overrides

extra:
  analytics:
    provider: custom